name: Build Expo APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK with Expo
        run: eas build --platform android --profile production --non-interactive

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: expo-apk
          path: ./build/app-release.apk

